[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"

[dev]
  command = "npm run dev"
  port = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_DEFAULT_LOGIN_EMAIL = "superadmin@ivos.sn"
  VITE_DEFAULT_LOGIN_PASSWORD = "SuperAdmin@IVOS2026"

[context.staging.environment]
  NODE_ENV = "production"
